name: Check project source for Maven
on:
  push:
#    outputs:
#      maven:
#        description: "determines whether maven exists or not"
#        value: ${{ jobs.check_for_maven.outputs.maven }}

jobs:
  check_for_maven:
    outputs:
      maven: ${{steps.maven-test.outputs.maven}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source for checking maven script
        uses: actions/checkout@v4
      - id: maven-test
        shell: bash
        name: analyse project for maven script
        run: test -f mvnw && echo maven=true || echo maven=false >> $GITHUB_OUTPUT


