name: Automated review using static analysis
on: workflow_call
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Check styling and conventions
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
