name: Automated review using static analysis
on: workflow_call
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@v0.9.6
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          locale: "US"
          reviewdog_flags: -filter-mode=file -fail-on-error
