name: Automated review using static analysis
on: workflow_call
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Check styling and conventions
        uses: dbelyaev/action-checkstyle@v0.9.6
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          level: warning
