name: Run unit and integration tests for build validation
on:
  push:
    branches-ignore:
      - main

jobs:
  check_for_gradle:
    uses: ./.github/workflows/analyse-for-gradle.yml
  check_for_maven:
    uses: ./.github/workflows/analyse-for-maven.yml
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source
        uses: actions/checkout@v4
