name: Run unit and integration tests for build validation
on:
  push:
    branches-ignore:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source
        uses: actions/checkout@v4
      - name: Check project for Gradle script
        uses: ./.github/workflows/analyse-for-gradle.yml
      - name: Check project for Maven script
        uses: ./.github/workflows/analyse-for-maven.yml
