name: Build test for pull request
on:
  push:
    branches-ignore:
      - main

jobs:
  check_for_gradle:
    name: Check for gradle script
    uses: ./.github/workflows/analyse-for-gradle.yml
  check_for_maven:
    name: Check for maven script
    uses: ./.github/workflows/analyse-for-maven.yml
  run_tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source
        uses: actions/checkout@v4
