name: Deploy to docker
on:
  push:
    branches:
      - dev
      - main
jobs:
  check_for_gradle:
    name: Check for gradle script
    uses: ./.github/workflows/analyse-for-gradle.yml
  check_for_maven:
    name: Check for maven script
    uses: ./.github/workflows/analyse-for-maven.yml
  deploy:
    name: push to registry
    runs-on: ubuntu-latest
    needs:
      - check_for_gradle
      - check_for_maven
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push using gradle build tool
        if: ${{ needs.check_for_gradle.outputs.gradle == 'true'}}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/app:latest
          build-args: |
            mainClass=com.example.cicdDemo.CicdDemo
          target: gradle-build
      - name: Build and push using maven build tool
        if: ${{ needs.check_for_maven.outputs.maven == 'true'}}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/app:latest
          build-args: |
            mainClass=com.example.cicdDemo.CicdDemo
          target: maven-build
